//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerEntities : DbContext
    {
        public PowerEntities()
            : base("name=PowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TA_MENU> TA_MENU { get; set; }
        public virtual DbSet<TL_BASEDATA> TL_BASEDATA { get; set; }
        public virtual DbSet<TS_BUTTON> TS_BUTTON { get; set; }
        public virtual DbSet<TS_DEPT> TS_DEPT { get; set; }
        public virtual DbSet<TS_MENU> TS_MENU { get; set; }
        public virtual DbSet<TS_OPER_ROLE> TS_OPER_ROLE { get; set; }
        public virtual DbSet<TS_OPERATOR> TS_OPERATOR { get; set; }
        public virtual DbSet<TS_PORTAL> TS_PORTAL { get; set; }
        public virtual DbSet<TS_ROLE> TS_ROLE { get; set; }
        public virtual DbSet<TS_ROLE_NOTIFYTYPE> TS_ROLE_NOTIFYTYPE { get; set; }
        public virtual DbSet<TS_ROLE_POWER> TS_ROLE_POWER { get; set; }
        public virtual DbSet<VS_OPER_ROLE> VS_OPER_ROLE { get; set; }
        public virtual DbSet<VS_POWER_MENU> VS_POWER_MENU { get; set; }
    }
}
