//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterfaceEntities : DbContext
    {
        public InterfaceEntities()
            : base("name=InterfaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OA_PART> OA_PART { get; set; }
        public virtual DbSet<OA_PO_MAIN> OA_PO_MAIN { get; set; }
        public virtual DbSet<OA_PO_SUB> OA_PO_SUB { get; set; }
    }
}
