//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PART
    {
        public int UID { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string engname { get; set; }
        public string model { get; set; }
        public string partType { get; set; }
        public string unit { get; set; }
        public Nullable<int> enabled { get; set; }
        public string groupcode { get; set; }
        public string goodcode { get; set; }
        public string address { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public byte[] annex { get; set; }
        public string wladdress { get; set; }
        public string buyer { get; set; }
        public string drawingnum { get; set; }
        public Nullable<int> IsSyn { get; set; }
    }
}
