//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PO_SUB
    {
        public int UID { get; set; }
        public Nullable<int> OAMainID { get; set; }
        public string prdetailid { get; set; }
        public Nullable<decimal> taxval { get; set; }
        public string itemenname { get; set; }
        public Nullable<decimal> tatal1 { get; set; }
        public string namespecification { get; set; }
        public string no { get; set; }
        public string itemnumber { get; set; }
        public string itemname { get; set; }
        public string specification { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string um { get; set; }
        public Nullable<decimal> purcose { get; set; }
        public string plno { get; set; }
        public Nullable<decimal> popurcose { get; set; }
        public string taxate { get; set; }
        public Nullable<decimal> taxamount { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> tatal { get; set; }
        public string site { get; set; }
        public Nullable<bool> provisonalprice { get; set; }
        public string remark { get; set; }
        public string acct { get; set; }
        public string subacct { get; set; }
        public string costcenter { get; set; }
        public string programcode { get; set; }
        public string req { get; set; }
        public string prln { get; set; }
        public string reqby { get; set; }
        public string inventoryparts { get; set; }
    }
}
