//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_PO_MAIN
    {
        public int UID { get; set; }
        public Nullable<int> OAID { get; set; }
        public string supplieradd { get; set; }
        public string currencydescribe { get; set; }
        public string engtitle { get; set; }
        public string subject { get; set; }
        public string entitychname { get; set; }
        public string costcenterdecribe { get; set; }
        public string billtobank { get; set; }
        public string billtotax { get; set; }
        public Nullable<decimal> nontaxable { get; set; }
        public string orderno { get; set; }
        public string entityenname { get; set; }
        public string billtoaccounts { get; set; }
        public string billtofax { get; set; }
        public Nullable<decimal> taxable { get; set; }
        public Nullable<System.DateTime> orderate { get; set; }
        public string entityadd { get; set; }
        public string billtoadd { get; set; }
        public Nullable<decimal> totalfax { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string entityenadd { get; set; }
        public string buyer { get; set; }
        public string entitypostcode { get; set; }
        public string @operator { get; set; }
        public string entityfax { get; set; }
        public string entityname { get; set; }
        public string entitytel { get; set; }
        public string billto { get; set; }
        public string suppliercode { get; set; }
        public string fob { get; set; }
        public string suppliername { get; set; }
        public string applicant { get; set; }
        public string buyername { get; set; }
        public string shipto { get; set; }
        public string paymentode { get; set; }
        public string theapplicantphone { get; set; }
        public string paymentdescribe { get; set; }
        public string remark { get; set; }
        public string printorderdate { get; set; }
        public byte[] affix { get; set; }
        public Nullable<System.DateTime> printduedate { get; set; }
        public string supplier { get; set; }
        public string attn { get; set; }
        public string currency { get; set; }
        public string paymentterm { get; set; }
        public Nullable<bool> paytax { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string bank { get; set; }
        public Nullable<decimal> toal { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> isinvalid { get; set; }
        public Nullable<bool> construction { get; set; }
        public Nullable<int> IsSyn { get; set; }
    }
}
