//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Attach
    {
        public int UID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TablePKID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatorName { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
    }
}
