//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_BILLTYPE
    {
        public int UID { get; set; }
        public int BillType { get; set; }
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
        public int State { get; set; }
        public string Prefix { get; set; }
        public string BillNumRule { get; set; }
        public int LastNumber { get; set; }
        public string LastBillNum { get; set; }
        public System.DateTime LastBillTime { get; set; }
        public string PrintTemplateFileName { get; set; }
        public string ImportTemplateFileName { get; set; }
        public Nullable<bool> IsCalc { get; set; }
    }
}
