//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_EQUIPMENT
    {
        public long UID { get; set; }
        public string EqptCode { get; set; }
        public string EqptName { get; set; }
        public string EqptType { get; set; }
        public string EqptModel { get; set; }
        public string EqptLocation { get; set; }
        public string DeptCode { get; set; }
        public string EqptManager { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
    }
}
