//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_LINESTATION
    {
        public string LineName { get; set; }
        public string LineCode { get; set; }
        public string StationName { get; set; }
        public string StationCode { get; set; }
        public Nullable<bool> IsOrNotCollection { get; set; }
        public Nullable<bool> IsOrNotInspectionOrder { get; set; }
        public Nullable<bool> IsOrNotFirstOrder { get; set; }
        public Nullable<bool> IsOrNotCompleted { get; set; }
        public Nullable<bool> IsOrNotResetFlag { get; set; }
        public Nullable<bool> IsOrNotScan { get; set; }
        public Nullable<bool> IsOrNotCom { get; set; }
        public int ID { get; set; }
    }
}
