//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_LINE
    {
        public string LineName { get; set; }
        public string LineCode { get; set; }
        public string OwnedWorkshopCode { get; set; }
        public string OwendProcessCode { get; set; }
        public int State { get; set; }
        public int ID { get; set; }
    }
}
