//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_MACHINE
    {
        public long UID { get; set; }
        public string MachineCode { get; set; }
        public string MachineName { get; set; }
        public string MachineType { get; set; }
        public string MachineModel { get; set; }
        public string MachineLocation { get; set; }
        public string DeptCode { get; set; }
        public string Manager { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
    }
}
