//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_PART
    {
        public long UID { get; set; }
        public string PartCode { get; set; }
        public string ErpPartCode { get; set; }
        public string PartDesc1 { get; set; }
        public string PartDesc2 { get; set; }
        public string Unit { get; set; }
        public string BM { get; set; }
        public int PartType { get; set; }
        public decimal MaxQty { get; set; }
        public decimal MinQty { get; set; }
        public decimal SafeQty { get; set; }
        public int IdleDays { get; set; }
        public decimal SplyPackQty { get; set; }
        public int ValidityDays { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
        public byte[] Picture { get; set; }
    }
}
