//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SUPERLIER
    {
        public int UID { get; set; }
        public string SplyId { get; set; }
        public string SplyName { get; set; }
        public string ErpCode { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Contacter { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int State { get; set; }
        public string Remark { get; set; }
    }
}
