//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OTHER_OUT
    {
        public int UID { get; set; }
        public string BillNum { get; set; }
        public string PartCode { get; set; }
        public string Batch { get; set; }
        public string FromLocCode { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Remark { get; set; }
    }
}
