//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_INTERFACE
    {
        public int UID { get; set; }
        public string InterfaceType { get; set; }
        public string InterfaceString { get; set; }
        public int State { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ProcessTime { get; set; }
        public string BillNum { get; set; }
        public string BillType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> pQty { get; set; }
        public string p01 { get; set; }
        public string p02 { get; set; }
        public string p03 { get; set; }
        public string p04 { get; set; }
        public string p05 { get; set; }
        public string p06 { get; set; }
        public string p07 { get; set; }
        public string p08 { get; set; }
        public string p09 { get; set; }
        public string p10 { get; set; }
        public string p11 { get; set; }
        public string p12 { get; set; }
        public string p13 { get; set; }
        public string p14 { get; set; }
        public string p15 { get; set; }
        public string p16 { get; set; }
        public string p17 { get; set; }
        public string p18 { get; set; }
        public string p19 { get; set; }
        public string p20 { get; set; }
    }
}
