//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ROLE_POWER
    {
        public long UID { get; set; }
        public string RoleCode { get; set; }
        public string MenuCode { get; set; }
        public string PortalCode { get; set; }
        public bool IsVisible { get; set; }
        public bool IsReadOnly { get; set; }
    }
}
