//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_STOCK_DETAIL
    {
        public long UID { get; set; }
        public string 库位 { get; set; }
        public string 零件号 { get; set; }
        public string 批次 { get; set; }
        public int 状态 { get; set; }
        public decimal 数量 { get; set; }
        public decimal 单价 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public System.DateTime 生产日期 { get; set; }
        public System.DateTime 失效日期 { get; set; }
        public System.DateTime 更新时间 { get; set; }
        public decimal 更新数量 { get; set; }
    }
}
