//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CalSafeQty
    {
        public decimal 最低库存 { get; set; }
        public decimal 最高库存 { get; set; }
        public string 零件号 { get; set; }
        public string 零件描述 { get; set; }
    }
}
