//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_OVERDUE_STOCK
    {
        public string PartCode { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public string PartDesc1 { get; set; }
        public string PartDesc2 { get; set; }
        public string Unit { get; set; }
        public string BM { get; set; }
        public Nullable<int> PartType { get; set; }
        public Nullable<int> ValidityDays { get; set; }
        public System.DateTime ReceiveDate { get; set; }
    }
}
