//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangKeTec.Wms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VS_POWER_MENU
    {
        public long UID { get; set; }
        public string RoleCode { get; set; }
        public string MenuCode { get; set; }
        public string PortalCode { get; set; }
        public bool IsVisible { get; set; }
        public bool IsReadOnly { get; set; }
        public string ParentCode { get; set; }
        public string ControlType { get; set; }
        public string ControlName { get; set; }
        public string MenuText { get; set; }
        public string NameSpace { get; set; }
        public string ClassName { get; set; }
        public string Params { get; set; }
        public string ImageName { get; set; }
        public string Remark { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string BackColor { get; set; }
    }
}
